### ISSUE TITLE
Notifications appear in wrong language despite site language settings

### ISSUE THREAD

**Issue by danielzeljko** [LangCorrect/server#191]
I have my site language set to English, but I'm receiving notifications in Japanese. My initial assumption is that the notifications are appearing in the language setting of the sender, rather than adhering to my own site language settings.

![image](https://github.com/LangCorrect/server/assets/115326106/5d772103-a4ee-49d4-b2c0-397b30b80290)

**Comment by itshesam** [comment]
i was trying to find the bug and think i found it. You can assign it to me
but there were some other things that i found. The ```gettext``` seems to be case insensitive, so "corrected" was never got translated as we had "Corrected" in translations.
Also i didn't know we should generate translation binaries(```.mo``` files). We can add the generation command to the setup procedure in the document.
and another issue that i didn't know was that some words are translated in some locales but not in others(like "Corrected")

**Comment by danielzeljko** [comment]
I'm not really following -- `corrected` is showing in lowercase on my end. Can you please clarify or provide some examples?

![image](https://github.com/LangCorrect/server/assets/115326106/abe87724-395a-4d0e-bccf-c685d8f82282)

**Comment by itshesam** [comment]
i mistakenly said "case insensitive" instead of "case sensitive"

i meant that you can't see "corrected" in any other language except English, can you? because we had ```translate('correct')``` in the code and had a translation for "Corrected"(not "corrected") in our locale files. My point was we have to add some translation to our locale and update them for all languages.
