### ISSUE TITLE
Some sentences are not splitting correctly

### ISSUE THREAD

**Issue by socio-trivia** [LangCorrect/server#202]
Both single sentences and the passage including them are shown in Correction.
![115257](https://github.com/LangCorrect/server/assets/147959955/b83df0ae-1476-4619-9c19-b4627f89c285)
.

**Comment by keyxcode** [comment]
Thanks for the bug report @socio-trivia
Does this happen only in this journal or in all journals for you?

**Comment by socio-trivia** [comment]
Some Japanese entries are displayed in a single sentence, while others are displayed in a paragraph. This may be confusing for users, and it is unclear what your intended behavior is. It would be helpful to have feedback from other users on how these entries should be displayed.

**Comment by danielzeljko** [comment]
The intended behavior is for the text to be split into individual sentences. What we see here is actually a combination of a few things:
- OP is not terminating the sentences where they should, which **may** cause tokenization issues that prevent the sentences from splitting correctly (probably what happened with that long paragraph).
- The edits made by the OP caused some of the sentences to tokenize and split correctly. We can see that it's been edited by comparing the rows.
- Previous sentences that are no longer "present" in the text are not being hidden (the paragraph should be hidden).

If it's not too much trouble, can you please provide the link to the original post? We can take the text and run it manually through the sentence splitter to see what it spits out. I suspect that my original implementation may be naive because it assumes that students will always terminate their sentences correctly. NLP isn't easy, especially when dealing with text not written by native speakers or not composed properly. So, I'm open to suggestions here.

A few notes:
- The sentences are being split via signal `split_post_into_sentences`
- Japanese sentences are tokenized using `fugashi`
- The original implementation builds the string (sentence) until it reaches a Japanese terminator (。？！). At this point, it appends the completed sentence to a list and starts processing the next sentence.

![image](https://github.com/LangCorrect/server/assets/115326106/083a3bd3-dee6-4041-b949-7512c66400c0)
