### ISSUE TITLE
Background colors in corrections

### ISSUE THREAD

**Issue by keyxcode** [LangCorrect/server#205]
As a user, I really miss the light background colors that visually separated the corrections in the old site: light red for wrong sentences and light green for correct ones. Now they all share the same white background which makes it more difficult to tell them apart, and also causes eye fatigue.
I can't find a picture of the old interface, perhaps @danielzeljko can provide one as reference?
![image](https://github.com/LangCorrect/server/assets/102985900/2b1d7a18-ed3d-4aca-8689-218d6d6007a8)

**Comment by danielzeljko** [comment]
While the previous design made it easy to distinguish the corrected sentences, it consumed too much vertical space. IMO, this is problematic since over 68% of our users access LC on their mobile devices. We can find a compromise that minimizes vertical space usage while incorporating background colors to reduce eye strain. 

Another option is to maintain the current layout but switch the background color from white to an off-white shade. I'm open to suggestions. If someone wants to mock up some designs on Figma that would be epic.

As an aside, an easy way to distinguish the corrections apart in the new layout is to simply look for the check or cross icon.

![image](https://github.com/LangCorrect/server/assets/115326106/4d43ee1f-e5dd-44c4-a0a5-98b50a38a0aa)

**Comment by keyxcode** [comment]
Totally agree with you that the old design used too much space, which may negatively affect mobile use. I don't think that just changing the background colors will do this though, right? 
Here's a quick mock up I did directly in Boostrap using classic LC colors.
<img width="658" alt="image" src="https://github.com/LangCorrect/server/assets/102985900/f8d3d218-d451-4c48-8815-6a61f2c3bb1a">

**Comment by danielzeljko** [comment]
It won't -- you're right. I'm not sure why I thought you wanted the padding and the background colors back. Brain fart moment there. We'd just have to be careful to either pick background colors that are colorblind friendly or support colorblind mode in a later update.

**Comment by keyxcode** [comment]
What tools do you normally to check for colorblind compatibility @danielzeljko ? I only know of Chrome DevTools' color blindness emulator.

**Comment by danielzeljko** [comment]
I didn't even know dev tools had that. That's pretty neat. I've used this in the past: https://www.toptal.com/designers/colorfilter.
