### ISSUE TITLE
Bring back/ improve "Popular correctors" design

### ISSUE THREAD

**Issue by keyxcode** [LangCorrect/server#267]
Previous design:
<img width="433" alt="image" src="https://github.com/LangCorrect/server/assets/102985900/e265c43e-c7a5-4334-ad48-4f765fd7fde6">
Current:
<img width="425" alt="image" src="https://github.com/LangCorrect/server/assets/102985900/810c8417-4bce-4660-8f27-18b219fd1384">

**Comment by danielzeljko** [comment]
Thanks for the feedback! Let's bring back the old designs, but with a small adjustment. Let's remove the borders around the currently active tab, and just have an underline instead. I think this would make the widget look cleaner. Here's a quick example:

![image](https://github.com/LangCorrect/server/assets/115326106/cf5c123e-9f17-4378-8892-80c918d00c99)

We can use `primary` as the border color and maybe give it a height of 5px.

**Comment by keyxcode** [comment]
@danielzeljko 
As part of the old design I need to use the `display_name` of each user instead of their `username`. In order to do this, I believe I need to make changes to the `get_popular_correctors` and `aggregate_users` functions in `corrections/helpers.py` -- is that correct?

If that's the case, I don't think it's possible to use `user__display_name` because it's not actually a field. What should I do about this? Add it as a field to the User model?

**Comment by danielzeljko** [comment]
@keyxcode 

> As part of the old design I need to use the display_name of each user instead of their username. In order to do this, I believe I need to make changes to the get_popular_correctors and aggregate_users functions in corrections/helpers.py -- is that correct?

That's right.

> If that's the case, I don't think it's possible to use user__display_name because it's not actually a field. What should I do about this? Add it as a field to the User model?

I don't think we should create a field for this because then we would have to worry about keeping it in sync.

There are two approaches I can think of to solve this issue:

- The easiest way would be to fetch and append the `display_name` right before returning in `get_popular_correctors`. I'm not sure if this would be a good approach because it's basically like the `N+1` problem I mentioned before. However, it won't be a huge issue in this case because the limit we set is very small.

- The other approach would be to just refactor the code altogether as you mentioned. I'm sure there are a lot of ways to go about this, but one that comes to mind is [Case/When](https://docs.djangoproject.com/en/4.2/ref/models/conditional-expressions/#case). Here's something to get you started with this approach (double-check this):

```
PerfectRow.available_objects.filter(**filters).values('user').annotate(
        display_name=Case(
            When(user__nick_name__isnull=False, then=F("user__nick_name")),
            default=F("user__username"),
        ),
        num_corrections=Count('user'),
        slug=F("user__username")
    ).values('display_name', 'num_corrections', "slug")
```

Pay special attention to `slug` here. I added this because we need to actual username for redirecting to a profile.

**Comment by keyxcode** [comment]
Thanks for the detailed explanation @danielzeljko. I decided to go for the first option as it seems more straightforward and I think the number of extra N queries is small enough that's it's acceptable.
