### ISSUE TITLE
Page to view all posts you have corrected

### ISSUE THREAD

**Issue by danielzeljko** [LangCorrect/server#307]
> Dongchen
OP
 — Yesterday at 10:42 PM
It would be useful to have an overview of all posts to which I've made corrections, in order to improve in my criticism, or just for sentimental value. I haven't (yet) discovered such a functionality as a new user

**Comment by keyxcode** [comment]
1. I suppose this option will go here under My Prompts?
<img width="267" alt="image" src="https://github.com/LangCorrect/server/assets/102985900/31c2695b-9717-4c10-9ca7-1e2db9beb78c">
2. Assuming it also uses a table interface, what will the columns be? I'm thinking:
- Title
- Language
- Author
- Date (not sure if this should be date of publication or of correction)
- (The number of) Corrections made (maybe?)

**Comment by yue-dongchen** [comment]
1. That seems logical — e.g. "My Corrections"
2. Language would of course be useful. Perhaps the date of correction for now, since it's primarily about the user's correcting activities. With those additions it would be nice as a sortable table.

They're all easily retrievable from the PostgresSQL database, right? I have barely any programming knowledge.

**Comment by keyxcode** [comment]
Can I work on this? @danielzeljko
