### ISSUE TITLE
/journals/~create/ forbidden

### ISSUE THREAD

**Issue by korimart** [LangCorrect/server#326]
Hello, first of all thank you for this amazing project.

This issue is actually not mine but is from a new user who asked me how to use LangCorrect because he was getting "forbidden" when trying to access the URL for a new journal. The discussion is in the comment section between the new user (yidacode) and me (awawus): [please click](https://langcorrect.com/journals/%EA%B7%B8%EB%8F%99%EC%95%88-%EA%B3%A0%EB%A7%88%EC%9B%8C%EC%9A%94/). I am posting on his behalf because he seemed not comfortable working with Github.

I have no issue posting a new journal so maybe this is an issue for new comers?

Also, there seem to be some people who don't quite understand the prompt feature and leave their journals there instead (not as their journals but as prompts) receiving 0 corrections for days. This is very sad and I feel helpless because there are no ways to inform them about it.

Thank you for all your efforts into maintaining the project.

**Comment by danielzeljko** [comment]
The system automatically denies access to the new journal page when a user does not meet the minimum correction ratio **and** if there are uncorrected entries in their feed. See https://github.com/LangCorrect/server/blob/bed337494c89a343c965c9163fcaf68a9b121858/langcorrect/posts/helpers.py#L16

These checks are in place to ensure that users are contributing back and not just leeching corrections. Yidacode would need to correct Japanese journals found in their feed until they meet the minimum threshold. Otherwise, they can purchase a premium subscription to bypass the ratio watch or wait until there are no more uncorrected entries in their native language.

A message should have been included with the forbidden error, but IIRC it's only written in English. I'll create a ticket to make that string translatable.

Thank you for bringing the prompt issue to my attention. I'll create a tool to convert those writing prompts into actual journals and include a banner letting users know to not write journals there.

**Comment by korimart** [comment]
Thank you for such a quick response. I will forward the information to Yidacode!
