### ISSUE TITLE
Character limit bug

### ISSUE THREAD

**Issue by alexcjwei** [LangCorrect/server#336]
I'm trying to write a new journal, but get the invalid message: "You need to write 10 more characters to meet the minimum requirement."
I've verified that there are 10 characters in the textarea.

I've also tried reloading, retyping out the journal. I get different invalid messages depending on the configuration of my journal which is strange.

<img width="1352" alt="Screenshot 2023-12-18 at 10 38 06 AM" src="https://github.com/LangCorrect/server/assets/59217250/f273366d-d2f5-46fc-b302-59572e9617b8">

<img width="627" alt="Screenshot 2023-12-18 at 10 39 48 AM" src="https://github.com/LangCorrect/server/assets/59217250/86a3a3ca-55c9-4c37-a190-6b1445254314">

<img width="1335" alt="Screenshot 2023-12-18 at 10 45 57 AM" src="https://github.com/LangCorrect/server/assets/59217250/1e95701c-59fc-49c1-ab9a-c2d81ca430c6">

<img width="1315" alt="Screenshot 2023-12-18 at 10 45 48 AM" src="https://github.com/LangCorrect/server/assets/59217250/80ed6f87-bea5-4579-aee6-c4d09110d03b">

**Comment by danielzeljko** [comment]
There's a misunderstanding here. The error messages are informing you how many _additional_ characters you need to write in order to meet the minimum criteria (50). We have this mechanism in place to prevent low effort posts.

See: https://github.com/LangCorrect/server/blob/7958fefd78e4f6158117272866dc52fe626a2fde/langcorrect/posts/forms.py#L26

Do you have any suggestions to increase the clarity of the error message? Perhaps using some kind of progress would be good here (ie: 45/50 characters)

**Comment by alexcjwei** [comment]
Oof no tbh it's clear now, somehow my brain did not fully process the message
