### ISSUE TITLE
Developer setup issues

### ISSUE THREAD

**Issue by dgunay** [LangCorrect/server#467]
I recently bounced off of an attempt to contribute to your project due to several problems getting a development environment set up.

I began by proceeding down the readme from top to bottom. Here are the issues I encountered:

1. Install postgres & redis directly on the host machine. Gross, but easily worked around. I ran them with docker-compose and moved on.
2. Seeding the database. Option 1, as written, does not work because [fixtures/seed.sql does not exist](https://github.com/LangCorrect/server/tree/main/fixtures/seed.sql).
3. I proceed to Option 2. Immediately it doesn't work because I haven't installed any dependencies yet.
4. I check the readme. It doesn't say anything about how to install dependencies.
5. I see a `pyproject.toml` and assume the project uses `poetry`. I try `poetry install` and it fails because `[tool.poetry] section not found in /REDACTED/server/pyproject.toml`

At this point I give up, because I know how much of a mess dependency management is in Python and it feels like too much effort to contribute to the project.

I'm not saying this to be mean. LangCorrect is incredibly useful. 

If you want to encourage open source contributors though, you will lose far fewer people if you invest time in #182 or even just make it easier for newcomers to install Python dependencies (requirements.txt, pyproject.toml, whatever).

**Comment by danielzeljko** [comment]
Thanks for being interested in the project and for considering contributing to LC. I appreciate your feedback on the setup process. I'm actively working on the on-boarding experience for new contributors.

Re: dependency management, the readme does provide clear instructions on how to install it via a `requirements.txt` file. It must have been overlooked by accident:

> 3. Install the project dependencies for local development
> pip install -r requirements/local.txt

Additionally, progress in containerizing the project has been made as is evidenced by the latest comment](https://github.com/LangCorrect/server/issues/182#issuecomment-1913824232). However, the readme is pretty outdated at the moment, especially the segment on seeding the database. It is currently being addressed in #403. Both of these are expected to be addressed after the messenger feat is released. 

Here are some simplified instructions to get the project up and running (based on a recent setup I did for one of my machines):

1. Follow the steps until the LC database is created
2. Checkout #403 and run the following management command: `python manage.py setup_mock_data`. This will run the necessary migrations, install the fixtures, and generate some mock data. There is a small chance this script will fail due to faker not generating a unique username or email. In this case, just dropped the db and run the command again.
3. Install the JS dependencies: `npm i`
4. Run the project using `npm run dev`

I hope these instructions make the setup process smoother for you. If you happen to run into any issues, I'm more than happy to walk you through the process if you're still interested via our discord server.

**Comment by danielzeljko** [comment]
Hi @dgunay, I hope all is well. I just wanted to give you an update that there's a PR #491 that containerizes the project. If you don't mind, would you be up to giving it a test run? I've also updated the installation instructions. If you run into any issues, could you let me know? Otherwise, it'll be ready for merging!

**Comment by dgunay** [comment]
@danielzeljko Looks like it worked. Great stuff! I may try again next time the mood strikes.
