### ISSUE TITLE
Export issue

### ISSUE THREAD

**Issue by Anerneq** [LangCorrect/server#553]
Hello!

I was trying to export my corrections, but it seems like that's not possible anymore. I tried exporting them in PDF, but the website doesn't let me (it says there's an error, I tried it multiple times with multiple posts). I decided to try exporting them in CSV, but the Russian script is not supported, so I just get strings of random characters instead.

**Comment by danielzeljko** [comment]
I'm sorry about that.

I see the sentry events for it/replicated the issue. I'll work on a fix soon.

**Comment by Anerneq** [comment]
Hiya!

This is the text I was referring to: https://langcorrect.com/journals/%D1%83%D0%BF%D1%80%D0%B0%D0%B6%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BE%D0%B1-%D1%8D%D0%BC%D0%B8%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D0%B8-%D0%B2-%D0%B8%D1%81%D1%82%D0%BE%D1%80%D0%B8%D0%B8-%D1%84%D1%80%D0%B0%D0%BD%D1%86%D0%B8%D0%B8-%D0%B8-%D1%80%D0%BE%D1%81%D1%81%D0%B8%D0%B8/

My pc opened the file with Excel and this is what I see:
![Screenshot 2024-04-27 190439](https://github.com/LangCorrect/server/assets/168014253/1eda92d8-e811-4445-bad3-0e9b7a7b07aa)

I see the PDF export option works fine now, cheers!

**Comment by danielzeljko** [comment]
By default, our server exports CSV files with `UTF-8` encoding to ensure characters are displayed correctly in any language. However, there seems to be a common issue with Excel not opening files with `UTF-8` correctly. This can be seen in the links below with the number of users who have marked that they had the same question.

Here are a few methods to resolve this:

1. Explicitly open the file with a UTF-8 encoding: https://answers.microsoft.com/en-us/msoffice/forum/all/how-to-open-utf-8-csv-file-in-excel-without-mis/1eb15700-d235-441e-8b99-db10fafff3c2
2. (Advanced/Use caution) Set `UTF-8` as default in excel: https://answers.microsoft.com/en-us/msoffice/forum/all/excel-read-csv-set-utf-8-as-default-for-all-csv/62eb4068-fc70-4f9b-9bd7-c904713beaf0
3. (Easiest) Drag the files into Google Sheets because it handles the character encoding more effectively.
4. Use an alternative program

I hope this helps and I wish I was familiar with Excel to be able to help you out better :'( 

I'm also not sure what the yellow alert in your screenshot reads, maybe there's a way to open/configure the encoding when you follow the buttons?

I suggest to just use Google Sheets since it's free and works. The UI is also really similar. Here's a screenshot:

![image](https://github.com/LangCorrect/server/assets/115326106/3cda32ff-cdfd-4b3c-9f79-c0774633cfbc)

**Comment by Anerneq** [comment]
Cheers! 
I'll guess I'll just use Google Sheets then😅 It could maybe be a good idea to write it down in the selection menu, so users know that if they want a CSV file, it's best to use Google Sheets.

The yellow banner just says that some data could be lost since Excel can't interpret the data properly.
